USE AircraftControl

IF OBJECT_ID('dbo.Aeronaves', 'U') IS NOT NULL
DROP TABLE dbo.Aeronaves
GO

IF OBJECT_ID('dbo.ModelosAeronaves', 'U') IS NOT NULL
DROP TABLE dbo.ModelosAeronaves
GO

CREATE TABLE dbo.ModelosAeronaves
(
    CODE VARCHAR(4) NOT NULL PRIMARY KEY, -- primary key column
    ALTERNATIVE_CODE VARCHAR(4) UNIQUE,
    MAX_DEPARTURE_WEIGHT DECIMAL(10,3) NOT NULL,
    MAX_LANDING_WEIGHT DECIMAL(10,3) NOT NULL,    
);
GO

CREATE TABLE dbo.Aeronaves
(
    PREFIX VARCHAR(6) NOT NULL PRIMARY KEY, -- primary key column
    MAX_DEPARTURE_WEIGHT DECIMAL(10,3) NOT NULL,
    MAX_LANDING_WEIGHT DECIMAL(10,3) NOT NULL,
    ACTIVE BIT NOT NULL,
    AIRCRAFT_MODEL VARCHAR(4) NOT NULL FOREIGN KEY REFERENCES dbo.ModelosAeronaves(CODE)    
);
GO